# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config.
templates:
  params:
    author-name: Gabriel Majeri
    author-email: gabriel.majeri6@gmail.com
    copyright: MIT
    github-username: GabrielMajeri

install-ghc: false

system-ghc: true

compiler-check: newer-minor
skip-ghc-check: true

ghc-options:
  "$everything": -dynamic
